server:
  # 服务器访问端口
  port: 9090
  # 访问的基础路径
  context-path: /catchPerfer
logging:
  config: classpath:logback-spring.xml
spring:
  aop: 
    auto: true 
  datasource:
    primary: 
      url: jdbc:mysql://94.12.64.46:3306/kettle
      username: root
      password: mysql123
      driver-class-name: com.mysql.jdbc.Driver
      # 数据库连接池
      type: org.apache.commons.dbcp2.BasicDataSource
      initial-size: 5
      max-active: 20
      max-wait-millis: 10000
      min-idle: 5
      max-idle: 15
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8;autoReconnect=true;useAffectedRows=true
    secondary: 
      url: jdbc:oracle:thin:@94.12.73.35:1521:nxstqsyn
      username: hx_zgxt
      password: nxstqsy
      driver-class-name: oracle.jdbc.OracleDriver
      # 数据库连接池
      type: org.apache.commons.dbcp2.BasicDataSource
      initial-size: 5
      max-active: 20
      max-wait-millis: 10000
      min-idle: 5
      max-idle: 15
    thirdary: 
      url: jdbc:oracle:thin:@94.12.72.16:1521:nxstcxff1
      username: zj_wbcx
      password: cx123
      driver-class-name: oracle.jdbc.OracleDriver
      # 数据库连接池
      type: org.apache.commons.dbcp2.BasicDataSource
      initial-size: 2
      max-active: 20
      max-wait-millis: 10000
      min-idle: 2
      max-idle: 5
# 配置Mybatis的配置文件位置
mybatis:
  mapper-locations: classpath:mapper/*.xml 