-- ----------------------------
-- Table structure for R_RECORD_JOB
-- ----------------------------
DROP TABLE
IF EXISTS R_RECORD_JOB;

CREATE TABLE R_RECORD_JOB (
	UUID VARCHAR (64) NOT NULL,
	ID_JOB VARCHAR (255) NOT NULL,
	NAME_JOB VARCHAR (64) CHARACTER
SET utf8 COLLATE utf8_general_ci NOT NULL,
 ID_RUN VARCHAR (64) CHARACTER
SET utf8 COLLATE utf8_general_ci NULL,
 STATUS VARCHAR (64) CHARACTER
SET utf8 COLLATE utf8_general_ci NOT NULL,
 HOSTNAME VARCHAR (64) CHARACTER
SET utf8 COLLATE utf8_general_ci NULL,
 EXECUTION_TYPE VARCHAR (16) CHARACTER
SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'ONCE',
 CRON_EXPRESSION VARCHAR (16) CHARACTER
SET utf8 COLLATE utf8_general_ci NULL,
 ERROR_MSG VARCHAR (512) CHARACTER
SET utf8 COLLATE utf8_general_ci NULL,
 CREATE_TIME datetime NOT NULL,
 UPDATE_TIME datetime NOT NULL,
 PRIMARY KEY (ID_JOB, UUID)
) ENGINE = INNODB DEFAULT CHARACTER
SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Table structure for R_RECORD_HISTORY
-- ----------------------------
DROP TABLE
IF EXISTS R_RECORD_DEPENDENT;

CREATE TABLE R_RECORD_DEPENDENT (
	MASTER_UUID_ID VARCHAR (64) NOT NULL,
	META_ID VARCHAR (255) NOT NULL,
	META_TYPE VARCHAR (16) CHARACTER
SET utf8 COLLATE utf8_general_ci NOT NULL,
 CREATE_TIME datetime NOT NULL
) ENGINE = INNODB DEFAULT CHARACTER
SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Table structure for RECOMMEND_BASE_USER_TABLE
-- ----------------------------
DROP TABLE
IF EXISTS RECOMMEND_BASE_USER_TABLE;

CREATE TABLE RECOMMEND_BASE_USER_TABLE (
	USER_ID BIGINT NOT NULL,
	ITEM_ID BIGINT NOT NULL,
	SCORE DOUBLE NOT NULL
) ENGINE = INNODB DEFAULT CHARACTER
SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Table structure for RECOMMEND_BASE_ITEM_TABLE
-- ----------------------------
DROP TABLE
IF EXISTS RECOMMEND_BASE_ITEM_TABLE;

CREATE TABLE RECOMMEND_BASE_ITEM_TABLE (
	ITEM_ID BIGINT NOT NULL,
	ITEM_ID2 BIGINT NOT NULL,
	SCORE DOUBLE NOT NULL
) ENGINE = INNODB DEFAULT CHARACTER
SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Table structure for RECOMMEND_TASK_DEFINE
-- ----------------------------
DROP TABLE
IF EXISTS RECOMMEND_TASK_TRACK;

CREATE TABLE RECOMMEND_TASK_TRACK (
	ID VARCHAR (64) NOT NULL,
	STEP VARCHAR (64) NULL,
	STATUS VARCHAR (64) NULL,
	JOB_UUID VARCHAR (64) NULL,
	START_TIME datetime NULL,
	UPDATE_TIME datetime NULL,
	PRIMARY KEY (ID)
) ENGINE = INNODB DEFAULT CHARACTER
SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

INSERT INTO RECOMMEND_TASK_TRACK VALUES ("SQY00001",'FREE',NULL,NULL,NULL,NULL);

CREATE TABLE RECOMMEND_TASK_SUB_TRACK (
	ID VARCHAR (64) NOT NULL,
	STEP VARCHAR (64) NULL,
	STATUS VARCHAR (64) NULL,
	JOB_UUID VARCHAR (64) NULL,
	START_TIME datetime NULL,
	UPDATE_TIME datetime NULL,
	PRIMARY KEY (ID)
) ENGINE = INNODB DEFAULT CHARACTER
SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

